version: '3.8'

networks:
  internal:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    volumes:
      - ./:/app
    networks:
      - internal

  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

    networks:
      - internal

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - internal