# Generated by Django 4.2.5 on 2023-10-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetroleumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('petroleum_product', models.CharField(max_length=255)),
                ('sale', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
